server:
  port: 8080

spring:
  application:
    name: sse-learn-backend
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    
  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed-headers: ["*"]
      allow-credentials: true

logging:
  level:
    com.example.sselearn: DEBUG
    org.springframework.web: DEBUG